### ISSUE TITLE
Use more nasty adjectives

### ISSUE THREAD

**Issue by michaelkrone** [michaelkrone/raider#2]
I think we could use some more nasty adjectives, what do you think?

**Comment by hendrichbenjamin** [comment]
A lot more. The results are currently pretty repetitive.
Also, we should clean out adjectives that not quite match our requirements, such as "annoy" or "don't".

**Comment by michaelkrone** [comment]
Agee.
[This](https://www.englishclub.com/vocabulary/adjectives-personality-negative.htm) looks good, maybe I can merge some in and filter some out. Do we need a build Script for those Tasks?. I cannot assign myself on mobile, will close this later.

**Comment by hendrichbenjamin** [comment]
I did some cleaning, should be good now, I think.
That list looks very good. Merging those in should boost our negativity quite a bit.

**Comment by michaelkrone** [comment]
Closed with ff072b23

**Comment by michaelkrone** [comment]
Reopen, sorry for the noise

**Comment by michaelkrone** [comment]
Unethically Unreliable Unicorn!
Closed with 3c51e3a9b4886d1cce14e867ea904d8f0b7e9d5d
