### ISSUE TITLE
Add positive adjectives

### ISSUE THREAD

**Issue by hendrichbenjamin** [michaelkrone/raider#3]
Maybe someone would like some more positive energy in their names. Should we add another category and an option for that?

**Comment by 007300** [comment]
Either positive or negative should not be a problem. Something weird looks interesting.

**Comment by michaelkrone** [comment]
Positive energy? Totally out of scope for this project! 😂
What about `--mood=[positive|realistic]` and categorize the word Arrays accordingly, at least the adjectives/adverbs.

**Comment by hendrichbenjamin** [comment]
--mood=[utopic|realistic] might be a good call.

**Comment by michaelkrone** [comment]
Excellent!

**Comment by michaelkrone** [comment]
Closed with #5
